config = {'lr'           : 0.5,
          'epochs'       : 50,
          'input_size'   : 28*28,
          'hidden_units' : 64,
          'output_size'  : 10,
          'batch_size'   : 64,
          'training_size': 60000,
          'Debug'        : True,
          'isShuffle'    : True,
          'n_filter'     : 10,
          'w_filter'     : 7,
          'h_filter'     : 7,
          'stride'       : 1,
          'padding'      : 1,
          'img_size'     : 28,
          'beta'         : 0.9}
